config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :cats

  resources :tasks do
    member do
      get 'complete'
    end
  end
  

  root 'tasks#index'
end

app/models/cat.rb
class Cat < ActiveRecord::Base
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception 	
 # protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  #  protect_from_forgery unless: -> { request.format.json? }
 # protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  #after_filter :set_access_control_headers

  # def self.allow_cors(*methods)
  #   before_filter :cors_before_filter, :only => methods
  #   skip_before_action :verify_authenticity_token

  #   # Rails recommends to use :null_session for APIs
  #   # protect_from_forgery with: :null_session, :only => methods
  # end

protect_from_forgery with: :exception

  # def set_access_control_headers
  #   headers['Access-Control-Allow-Origin'] = "*"
  #   headers['Access-Control-Request-Method'] = %w{GET POST OPTIONS}.join(",")
  # end

  # def cors_before_filter
  #   # Check that the `Origin` field matches our front-end client host
  #   if /\Ahttps?:\/\/localhost:8888\z/ =~ request.headers['Origin']
  #     headers['Access-Control-Allow-Origin'] = request.headers['Origin']
  #     headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS' # allow GET POST and OPTIONS
      
  #   end
  # end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]
  skip_before_filter :verify_authenticity_token

  # allow_cors :index,:show,:create
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html { }
      format.json { render :json => @tasks, :callback =>params[:callback]}
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    data = Task.all
    format.json { render :json => data, :callback =>params[:callback]}
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @task.complete = true
    @task.save
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :desc, :complete, :cat_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/cats/_form.html.erb
<%= simple_form_for(@cat) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<div class="page-header">
  <%= link_to cats_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @cat, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing cat</h1>
</div>

<%= render 'form' %>

app/views/cats/index.html.erb
<div class="page-header">
  <%= link_to new_cat_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Cat
  <% end %>
  <h1>Listing cats</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @cats) do |cat| %>
            <td><%= cat.name %></td>
            <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cats/new.html.erb
<div class="page-header">
  <%= link_to cats_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New cat</h1>
</div>

<%= render 'form' %>

app/views/cats/show.html.erb
<div class="page-header">
  <%= link_to cats_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_cat_path(@cat), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show cat</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @cat.name %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ToDo", "/tasks#index", :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/cats#index">Categories</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :complete %>
    <%= f.collection_select(:cat_id, Cat.all, :id, :name) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <%= link_to tasks_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @task, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <%= link_to new_task_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Task
  <% end %>
  <h1>Listing tasks</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Desc</th>
            <th>Complete</th>
            <th>Cat</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tasks) do |task| %>
            <td><%= task.name %></td>
            <td><%= task.desc %></td>
            <td>

              <% if task.complete == false%>
                  <% link_to complete_task_path(task), :class => 'btn btn-default', remote: true %>
                      <span class="btn-default btn glyphicon glyphicon-ok"></span>
                   
              <% else%>
                <span class="btn-default btn disabled glyphicon glyphicon-ok"></span>
              <%end%>
              
           </td>
            <td><%= task.cat.name %></td>
            <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<div class="page-header">
  <%= link_to tasks_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New task</h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <%= link_to tasks_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_task_path(@task), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show task</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @task.name %></dd>

  <dt>Desc:</dt>
  <dd><%= @task.desc %></dd>

  <dt>Complete:</dt>
  <dd><%= @task.complete %></dd>

  <dt>Catid:</dt>
  <dd><%= @task.cat_id %></dd>

</dl>